name = "#NAME"
type = "javascript"
zone_id = ""
account_id = "#ACCID"

workers_dev = true
compatibility_date = "2022-02-01"

[build]
command = "clear && npm run build"
[build.upload]
format = "service-worker"